name: Deploy Next.js App to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t ashleywpc/next-ec2-cicd .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Image to Docker Hub
        run: docker push ashleywpc/next-ec2-cicd

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull ashleywpc/next-ec2-cicd
      - name: Delete Old Container
        run: docker rm -f nextjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nextjs-app-container ashleywpc/next-ec2-cicd